(require "./stones/journeyman/client.arc")

(def create-mason (username password email)
  (pr (string (post-url "localhost:9999/createmason" (list 'username username 'password password 'email email))))
)
(def upload-stone (stonename files)
    (prn "Upload stone: @stonename")
    (prn "Files to upload" (type files))    
    (pr (string (upload-file "localhost:9999/createstone" (list 'stonename stonename) files )))
)